/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRelayedBasePool,
  IRelayedBasePoolInterface,
} from "../IRelayedBasePool";

const _abi = [
  {
    inputs: [],
    name: "getRelayer",
    outputs: [
      {
        internalType: "contract IBasePoolRelayer",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRelayedBasePool__factory {
  static readonly abi = _abi;
  static createInterface(): IRelayedBasePoolInterface {
    return new utils.Interface(_abi) as IRelayedBasePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRelayedBasePool {
    return new Contract(address, _abi, signerOrProvider) as IRelayedBasePool;
  }
}
